### ISSUE TITLE
W5-2的代码跑不通啊

### ISSUE THREAD

**Issue by tx-pmy** [kpyaoqi/chaincamp#14]
Error: Transaction reverted: function call to a non-contract account
    at UniswapV2Router02.getReserves (contracts/libraries/UniswapV2Library.sol:48)
    at UniswapV2Router02._addLiquidity (contracts/UniswapV2Router02.sol:47)
    at UniswapV2Router02.addLiquidityETH (contracts/UniswapV2Router02.sol:77)
    at MyTokenMarket.AddLiquidity (contracts/MyTokenMarket.sol:34)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at listOnTimeout (node:internal/timers:538:9)
    at processTimers (node:internal/timers:512:7)
    at HardhatNode._mineBlockWithPendingTxs (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1819:23)
    at HardhatNode.mineBlock (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:508:16)
    at EthModule._sendTransactionAndReturnHash (node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:1522:18)

**Comment by kpyaoqi** [comment]
具体参考https://blog.csdn.net/sanqima/article/details/121875309这个链接.

**Comment by tx-pmy** [comment]
好的， 已经清楚了， 谢谢大佬
